[1.4.4]
Title = "Version 1.4.4"
Description = [ "Something went wrong with the source code.  Still points to 1.2.0.  Bump version to publish correct source.",]

[1.4.3]
Title = "Version 1.4.3"
Description = [ "Correct the camelCase naming convention according to PEP8", "The module name was changed to camelCase as an experiment.  This is a mess.  Changed it back.",]

[1.4.2]
Title = "Version 1.4.2"
Description = [ "Add the necessary testing for the module.",]

[1.4.1]
Title = "Version 1.4.1"
Description = [ "Creation of the project", "List all the changes to the project here.", "Changes listed here will be in the release notes under the above heading.",]
